# name: "composite action analysis tool"
# inputs:
#   working-directory:  # id of input
#     required: false
#     default: ''

# runs:
#   using: "composite"
#   steps:
#     - name: checkout
#       uses: actions/checkout@v5
#     - name: Build with Maven
#       run: mvn -B verify checkstyle:checkstyle
#       working-directory: ${{ inputs.working-directory }}
#     - uses: jwgmeligmeyling/checkstyle-github-action@master
#       with:
#         path: '**/checkstyle-result.xml'
#     - name: Run Unit Tests
#       run: mvn test
#       working-directory: ${{ inputs.working-directory }}